ecommapp/urls.py
from django.conf.urls import url,include
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin




userurls=[
   url(r'user-dashboard/$',UserDashboard.as_view(),name="user-dashboard"),
   url(r'edit-info/$',EditFormView.as_view(),name="edit-form"),
   url(r'security/$',SecurityView.as_view(),name="security"),
   url(r'credits/$',FashVoltsCreditView.as_view(),name="credits"),
   url(r'coupon-applied/$',CoupounAppliedView.as_view(),name="coupons"),
 #  url(r'reviews/$',UserReviewList.as_view(),name="user-reviews"),
   url(r'past-orders/$',UserOrderList.as_view(),name="user-orders"),
   url(r'returned-orders/$',ReturnedOrderList.as_view(),name="user-returned-orders-list"),
   url(r'request/return-orders/$',ReturnOrderAPI.as_view(),name="return-orders")
]

authurls=[
    url(r'register/$',RegisterView.as_view(),name="register"),
    url(r'signin/$',SignInView.as_view(),name="signin"),
    url(r'signout/$',SignOutView.as_view(),name="signout"),

]

carturls=[
    url(r'^$',PostGetCartView.as_view(),name="cart"),
    url(r'delete/$',DeleteCartView.as_view(),name="cartdelete"),
    url(r'checkout/$',CheckoutView.as_view(),name="checkout"),
    url(r'apply-coupon/$',ApplyCoupon.as_view(),name="apply-coupon"),
    url(r'apply-credit/$',creditapply,name="apply-credit"),
    url(r'remove-credit/$',removeapply,name="remove-credit"),
]
wishlisturls=[
  url(r'product/$',GetPostToWishlist.as_view(),name="wishlist"),
  url(r'product-count/$',GetToWishListCount,name="wishlist-count"),
  url(r'delete/$',DeleteFromWishList.as_view(),name="delete-wishlist"),

]

commonurls=[
    url(r'^$',HomeView.as_view(),name="home"),
    url(r'product/(?P<basefield>[\w-]+)/(?P<subfield>[\w-]+)/$',ProductList.as_view()),
    url(r'product/(?P<basefield>[\w-]+)/(?P<subfield>[\w-]+)/(?P<pk>\w+)$',ProductDetails.as_view()),
]

orderurls=[
url(r'place-order/$',PlaceOrder.as_view(),name="place-order"),
url(r'cancel-order/$',CancelOrder.as_view(),name="cancel-order"),
url(r'order-payment/(?P<order_id>\d+)/$',OrderPayment.as_view(),name="order-payment"),
url(r'invoice/(?P<order_id>\d+)/$',Invoice_View,name="invoice")
]

adminurls=[
   url(r'signin/$',AdminSignin.as_view(),name="admin-login"),
   url(r'^$',AdminPanel.as_view(),name="admin-panel"),
   url(r'signout/$',AdminSignOut.as_view(),name="admin-signout"),
   url(r'catalog/basecategories/$',AdminBaseCategory.as_view(),name="admin-catalog-base"),
   url(r'catalog/create-basecategories/$',AdminBasecategoryCreateView.as_view(),name="admin-catalog-base-new"),
   url(r'catalog/edit-basecategories/(?P<pk>[0-9]+)$',AdminBasecategoryUpdateView.as_view(),name="admin-catalog-base-edit"),
   url(r'catalog/edit-basecategories/delete/$',AdminBasecategoryDeleteView.as_view(),name="admin-catalog-base-delete"),
   url(r'catalog/subcategories/$',AdminSubCategory.as_view(),name="admin-catalog-sub"),
   url(r'catalog/create-subcategories/$',AdminSubcategoryCreateView.as_view(),name="admin-catalog-sub-new"),
   url(r'catalog/edit-subcategories/(?P<pk>[0-9]+)$',AdminSubcategoryUpdateView.as_view(),name="admin-catalog-sub-edit"),
   url(r'catalog/edit-subcategories/delete/$',AdminSubcategoryDeleteView.as_view(),name="admin-catalog-sub-delete"),
   url(r'catalog/products/$',AdminProduct.as_view(),name="admin-catalog-product"),
   url(r'catalog/edit-products/$',AdminProductCreateView.as_view(),name="admin-catalog-product-new"),
   url(r'catalog/edit-products/(?P<pk>[\w-]+)$',AdminProductUpdateView.as_view(),name="admin-catalog-product-edit"),
   url(r'catalog/edit-products/delete/$',AdminProductDeleteView.as_view(),name="admin-catalog-product-delete"),
   url(r'catalog/products-pics/$',AdminProductPics.as_view(),name="admin-catalog-product-pics"),
   url(r'catalog/edit-products-pics/$',AdminProductPicsCreateView.as_view(),name="admin-catalog-product-pics-new"),
   url(r'catalog/edit-products-pics/(?P<pk>[\w-]+)$',AdminProductPicsUpdateView.as_view(),name="admin-catalog-product-pics-edit"),
   url(r'catalog/edit-products-pics/delete/$',AdminProductPicsDeleteView.as_view(),name="admin-catalog-product-pics-delete"),
   url(r'customer/sellers/$',AdminSellers.as_view(),name="admin-customer-sellers"),
   url(r'customer/edit-sellers/$',AdminSellersCreateView.as_view(),name="admin-customer-sellers-new"),
   url(r'customer/edit-sellers/(?P<pk>[\w-]+)$',AdminSellersUpdateView.as_view(),name="admin-customer-sellers-edit"),
   url(r'customer/edit-sellers/delete/$',AdminSellersDeleteView.as_view(),name="admin-customer-sellers-delete"),
   url(r'customer/enduser/$',AdminCustomer.as_view(),name="admin-customer-enduser"),
   url(r'marketing/coupon/$',AdminCoupon.as_view(),name="admin-marketing-coupon"),
   url(r'marketing/edit-coupon/$',AdminCouponCreateView.as_view(),name="admin-marketing-coupon-new"),
   url(r'marketing/edit-coupon/(?P<pk>[\w-]+)$',AdminCouponUpdateView.as_view(),name="admin-marketing-coupon-edit"),
   url(r'marketing/edit-coupon/delete/$',AdminCouponDeleteView.as_view(),name="admin-marketing-coupon-delete"),
   url(r'admin-order/$',AdminOrderView.as_view(),name="admin-order"),
   url(r'admin-order/order-list-by-category$',AdminOrderViewByCategory.as_view(),name="admin-order-by-category"),
   url(r'admin-order/order-list-by-category/(?P<subfield>[\w-]+)$',AdminOrderViewByGivenCategory.as_view(),name="admin-order-by-given-category"),
   url(r'admin-order/change-product-status$',OrderProductStatusChange.as_view(),name="admin-order-product-status"),
   url(r'admin-order/change-order-status$',WholeOrderPaymentConfirm.as_view(),name="admin-order-status"),
   url(r'admin-reports/total-order$',AdminReportsOrderView.as_view(),name="admin-reports-orders"),
   url(r'admin-reports/get-order-stats$',OrderReportApi.as_view(),name="admin-reports-orders-stats"),
   url(r'admin-reports/total-users$',AdminReportsUserView.as_view(),name="admin-reports-users"),
   url(r'admin-reports/get-user-stats$',UserReportApi.as_view(),name="admin-reports-users-stats"),
   url(r'admin-order/returned-orders$',AdminReturnedOrders.as_view(),name="admin-return-orders"),
]

salesurls=[
 url(r'signin/$',SalesSignin.as_view(),name="sales-signin"),
 url(r'^$',SalesPanel.as_view(),name="sales-panel"),
 url(r'signout/$',SalesSignOut.as_view(),name="sales-signout"),

]

customurls=[

 url(r'^$',CustomView.as_view(),name="sales-panel"),


]
custommoduleurls=[
 url(r'brand/(?P<type>[\w-]+)$',CustomModule.as_view(),name="custom-home"),
 url(r'edit/(?P<pk>[\w]+)$',CustomeModuleMain.as_view(),name="edit-pic"),
 url(r'phone/(?P<brand_slug>[\w-]+)$',getphones,name="get-phones"),
 url(r'submit$',PostCustomModule.as_view(),name="submit-custom-image"),
 url(r'submit-images$',PostCustomModulePics.as_view(),name="submit-custom-working-images"),


]

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'cart/',include(carturls)),
    url(r'user/',include(userurls)),
    url(r'order/',include(orderurls)),
    url(r'search/',ElasticSearch,name="search"),
    url(r'admin-panel/',include(adminurls)),
    url(r'sales-panel/',include(salesurls)),
    url(r'custom/',include(customurls)),
    url(r'custom-module/',include(custommoduleurls)),
    url(r'wishlist/',include(wishlisturls)),
    url(r'^',include(commonurls)),
    url(r'^',include(authurls)),
  
]

ecommapp/models.py
# -*- coding: utf-8 -*-
#database for Fashvolts
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.base_user import BaseUserManager
from django.template.defaultfilters import slugify
from django.utils.crypto import get_random_string
from django.utils import timezone


class CustomUserManager(BaseUserManager):
    use_in_migrations = True
    def _create_user(self, username, password, **extra_fields):
        """
        Creates and saves a User with the given username, email and password.
        """
        if not username:
            raise ValueError('The given username must be set')
        username = self.model.normalize_username(username)
        user = self.model(username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, password, **extra_fields)

    def create_superuser(self, username, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(username, password, **extra_fields)



class CustomUser(AbstractBaseUser, PermissionsMixin):
    """
    Alll the users use this model to store their details
    username(//unique)
    profile Pic
    UUID(//automatically generated // auto increment// unique)
    password(AbstactBaseClass)
    """
    username=models.CharField(max_length=50,unique=True)
    is_active=models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    def get_full_name(self):
          return self.username

    def get_short_name(self):
          return self.username

    USERNAME_FIELD='username'
    REQUIRED_FIELD=['']

    objects=CustomUserManager()
    def __str__(self):
        return self.username



class BaseCategory(models.Model):
  Base_Category=models.CharField(max_length=100,unique=True)
  Base_Category_Pic=models.ImageField(upload_to="BaseCatPic/")
  Base_Slug_Field=models.SlugField(max_length=120,blank=True)
  def save(self, *args, **kwargs):
        print (self.Base_Category)
        self.Base_Slug_Field=slugify(self.Base_Category)
        super(BaseCategory, self).save()
  def __str__(self):
     return self.Base_Category



class SubCategory(models.Model):
  Base_category_Key=models.ForeignKey(BaseCategory)
  Sub_Category=models.CharField(max_length=100)
  Sub_Category_alias = models.CharField(max_length = 20, default = "sub")
  Sub_Category_Pic=models.ImageField(upload_to="SubCatPic/")
  Sub_Category_Slug_Field=models.SlugField(max_length=120,blank=True)
  def save(self, *args, **kwargs):
        self.Sub_Category_Slug_Field=slugify(self.Sub_Category)
        super(SubCategory, self).save()
  def __str__(self):
    return self.Sub_Category

class Tax(models.Model):
    Products=models.ForeignKey(SubCategory)
    Tax_Percentage=models.FloatField()
    

class Filter_Name(models.Model):
   Filter_Name=models.CharField(max_length=100)
   Filter_Subcategory_Type=models.ForeignKey(SubCategory)
   def __str__(self):
        return self.Filter_Name

class Filter_Category(models.Model):
   Filter=models.ForeignKey(Filter_Name)
   Filter_Category_Name=models.CharField(max_length=100)
   def __str__(self):
        return self.Filter_Category_Name

class Availibilty_status(models.Model):
  status=models.CharField(max_length=50,unique=True)
  def __str__(self):
        return self.status

class Seller(models.Model):
  seller_user=models.OneToOneField(CustomUser)
  Seller_Id=models.CharField(max_length=100,unique=True)
  Seller_Name=models.CharField(max_length=100)
  Address=models.TextField(max_length=500)
  Profile=models.TextField(max_length=1000)
  email=models.EmailField()
  Contact_Number=models.IntegerField()
  def __str__(self):
        return self.Seller_Id

class Shipment_Orgs(models.Model):
  Shipping_Company_Name=models.CharField(max_length=100)
  Shipping_Company_URL=models.URLField(max_length=100)
  def __str__(self):
        return self.Shipping_Company_Name
  #shipping company details will be added as per requirements
class Size(models.Model):
  size_sf=models.CharField(max_length=20)



class Product(models.Model):
  Product_Base_Category=models.ForeignKey(BaseCategory)
  product_Sub_Category=models.ForeignKey(SubCategory)
  Product_Name=models.CharField(max_length=200)
  Discount=models.FloatField(default=0)
  Base_Price=models.FloatField()
  Availiability=models.BooleanField(default=True)
  Description=models.TextField(max_length=10000,blank=True)
  Features=models.TextField(max_length=10000,blank=True)
  TechnicalSpecs=models.CharField(max_length=10000,blank=True)
  # Product_Filter=models.ManyToManyField(Filter_Category)
  Main_Image=models.ImageField(upload_to="ProductImages/")
  Shipment_Authority=models.ForeignKey(Shipment_Orgs)
  is_displayed=models.BooleanField(default=True)
  Product_Seller=models.ForeignKey(Seller)
  TaxOnProduct=models.ForeignKey(Tax)
  Sizes=models.ManyToManyField(Size)
  def __str__(self):
     return str(self.Product_Name)
  
  def get_product_url(self):
      return "product/"+str(self.Product_Base_Category.Base_Slug_Field)+"/"+str(self.product_Sub_Category.Sub_Category_Slug_Field)+"/"+str(self.pk)
  def price_after_discount(self):
      Actual_Price=((100-self.Discount)/100)* self.Base_Price
      price_after_tax=Actual_Price+((self.TaxOnProduct.Tax_Percentage/100)*Actual_Price)
      return  price_after_tax
  def indexing(self):
     from .search import ProductIndex
     obj = ProductIndex(
        meta={'id': self.id},
        Product_Name=self.Product_Name,
        Description=self.Description,
        Features=self.Features,
        TechnicalSpecs=self.TechnicalSpecs
     )
     obj.save()
     return obj.to_dict(include_meta=True)

class Flash_Sale(models.Model):
   Flash_Sale_Name=models.CharField(max_length=100)
   Products_In_Sale=models.ManyToManyField(Product)
   active=models.BooleanField(default=False)
   Main_Banner=models.ImageField(upload_to="FlashSaleBanner/")
   Flash_Sale_URL=models.URLField()
   def __str__(self):
     return self.Flash_Sale_Name




class Pics(models.Model):
  ProductPics=models.ForeignKey(Product)
  Images=models.ImageField(upload_to="ProductImages/")
  def __str__(self):
     return self.Images.name


class Customer(models.Model):
   User_customer=models.OneToOneField(CustomUser)
   Customer_First_Name=models.CharField(max_length=100)
   Customer_Last_Name=models.CharField(max_length=100)
   Customer_Email=models.CharField(max_length=100)
   Address_Line1=models.CharField(max_length=200)
   Address_Line2=models.CharField(max_length=200)
   City=models.CharField(max_length=200)
   State=models.CharField(max_length=200)
   ZIP=models.IntegerField()
   Customer_Contact_Number=models.IntegerField()
   Volts_Credit=models.IntegerField(default=0)
   User_Profile_Pic=models.ImageField(upload_to="UserProfilePic/",null=True)
   usability=models.BooleanField(default=True)
   can_create_custom=models.BooleanField(default=True)
   Join_Date_Time = models.DateTimeField(auto_now_add = True,blank = True)
   def __str__(self):
     return self.Customer_First_Name

# class Review(models.Model):
#   Reviewer=models.ForeignKey(Customer)
#   Product=models.ForeignKey(Product)
#   Review_Title=models.CharField(max_length=200)
#   Review_Body=models.TextField(max_length=5000)
#   show_review=models.BooleanField(default=True)

class Wish_List(models.Model):
   User_Wishlist=models.OneToOneField(CustomUser)


class Wish_List_Product(models.Model):
   Product_In_Wishlist=models.ForeignKey(Product)
   Wishlist=models.ForeignKey(Wish_List)


class Sales_Team(models.Model):
   Sales_user=models.OneToOneField(CustomUser)
   Sales_First_Name=models.CharField(max_length=100)
   Sales_Last_Name=models.CharField(max_length=100)
   Sales_Email=models.CharField(max_length=100)
   is_intern=models.BooleanField(default=False)
   Sales_Contact_Number=models.IntegerField()
   Sales_Points=models.IntegerField(default=0)
   def __str__(self):
     return self.Sales_First_Name

#coupon stuff
class CouponCode(models.Model):
    Code=models.CharField(max_length=100)
    Sales_Member=models.ForeignKey(Sales_Team,null=True,blank=True)
    Discount=models.FloatField(default=0)
    def __str__(self):
       return self.Code




class CustomerCouponUsed(models.Model):
    customer_track=models.ForeignKey(Customer)
    coupon_code=models.ForeignKey(CouponCode)

#cart stuff
class Cart(models.Model):
   date_of_creation=models.DateField(auto_now_add=True)
   checkout_date=models.DateField(blank=True,null=True)
   coupon_code=models.ForeignKey(CouponCode,null=True,blank=True)
   credits_used=models.IntegerField(default=0)
   def Total_cart_Price(self):
        total_cart_price=0
        for products in self.cartitem_set.all():
          total_cart_price+=products.Total_Price() 
        return total_cart_price
   def final_cart_price(self):
       bill=self.Total_cart_Price()
       if self.coupon_code:
          bill=bill-self.coupon_code.Discount
       if self.credits_used:

ecommapp/templates/base/admin-base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <link href={%static "css/bootstrap.min.css" %}  rel="stylesheet">
       {% block title %}
        {%endblock %}
      </head>
    <body>
       <div  class="container">
       <div class="col-md-4">
       {%if siteadmin %}
                  <a href={% url  "admin-signout"  %} >Logout</a>
                  <li>Hi {{siteadmin.username}}  </li>
          {%endif%}
           {% block body %}
           {%endblock%}
  <!--   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> -->
    <script src={%static "js/bootstrap.min.js" %}></script>
    <script src={%static "js/jquery.js" %}></script>
   <script src={%static "js/ajax.js"%}></script>
    {%block scripts%}
    {%endblock%}
  </body>
</html>

ecommapp/templates/base/header.html
{% load static %}
<!-- Navbar -->

<nav class="main-navbar hidden-xs hidden-sm">
      <div class="container-fluid">
              <div class="main-navbar-header">

                  <div class="logo">
                    <a href="/">
                      <img class="logo" src="{% static 'main/images/logo.png' %}" />
                    </a>
                  </div>
                  <div class="navbar-header-items">
                  <div class="other-navbar-header-items navbar-list hidden-xs hidden-sm">
                      <ul>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Contact Us</a></li>
                        <li><a href="#">Sell With Us</a></li>
                        <li><a href="#">Offers and deals</a></li>
                      </ul>
                  </div>
                  <div class="main-navbar-header-items">
                    <!-- Search bar -->
                    <div class="search-form">
                      <form class="main-navbar-form" action={%url "search" %} method="get">
                        <div class="input-group">
                          <input type="text" class="form-control" placeholder="Search" name="search_term">
                          <button type="button" name="button" class="btn btn-default search-btn" data-url="{% url "search" %}">
                            <i class="fa fa-search" aria-hidden="true"></i>
                          </button>
                        </div>
                      </form>
                    </div>
                    <!--Desktop buttons-->
                    <div class="main-navbar-more-buttons hidden-xs">
                          <a href='{%url "checkout" %}' class="header-cart-btn">
                              <i class="fa fa-shopping-cart" aria-hidden="true"></i> CART
                              <span class="cart-item-number badge"></span>
                            </a>
                            <a href={%url 'wishlist' %} class="header-wishlist-btn header-cart-btn">
                              <i class="fa fa-shopping-wishlist" aria-hidden="true"></i> WISHLIST
                              <span class="wishlist-item-number badge">0</span>
                            </a>
                  
                        <div class="dropdown">
                          {% if siteuser %}
                          <a href="" class="btn btn-default navbar-user-btn dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">
                            <i class="fa fa-user" aria-hidden="true"></i>
                            {{siteuser.customer.Customer_First_Name}}
                            <i class="fa fa-caret-down" aria-hidden="true"></i>
                          </a>
                          <ul class="dropdown-menu user-action-list">
                            <li><a href="{%url "user-dashboard"%}">Dashboard</a></li>
                            <li><a href="{%url "user-orders" %}">Orders</a></li>
                            <li><a href="{%url "coupons" %}">Your Coupons</a></li>
                            <li><a href="{%url "credits" %}">Your Credits</a></li>
                            <li><a href="{%url "signout" %}">Log Out</a></li>
                          </ul>
                            {% else %}
                            <a href="" class="btn btn-default navbar-user-btn dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">
                            <i class="fa fa-user" aria-hidden="true"></i>
                            MY ACCOUNT
                            <i class="fa fa-caret-down" aria-hidden="true"></i>

                          </a>
                          <ul class="dropdown-menu user-action-list">
                            <li><a href="/signin/">Login</a></li>
                            <li><a href="/register/">Sign Up</a></li>
                          </ul>
                          {%endif%}
                        </div>
                    </div>
                  </div>

                </div>

                  <div class="main-navbar-menu-list navbar-list" data-hover="dropdown" id="mainNavbar">
                      <ul>
                      {% for base in base_category_list%}
                            <li class="dropdown"><a href="{{category.category_name}}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ base.Base_Category }}</a>
                              <ul class="dropdown-menu">
                                {% for  sub in base.subcategory_set.all %}

                                    <li><a href="/product/{{base.Base_Category|lower}}/{{sub.Sub_Category|lower}}/">{{sub.Sub_Category_alias}}</a></li>

                                {% endfor %}
                              </ul>
                            </li>
                        {% endfor %}
                      </ul>
                  </div>
              </div>

      </div>
</nav>
<!-- for mobile -->
<nav class="main-navbar visible-xs visible-sm">
    <div class="container-fluid">
      <div class="main-navbar-header">
        <div class="main-toggle-button">
            <button id="navbar-toggle-button" class="main-navbar-button visible-xs-inline btn btn-default small-button">
                  <i class="fa fa-bars" aria-hidden="true"></i>
            </button>
        </div>

        <div class="logo">
          <a href="/">
            <img class="logo" src="{% static 'main/images/logo.png' %}" />
          </a>
        </div>

        <button class="btn btn-default navbar-cart-btn">
          <a href="{%url "checkout"%}">
              <i class="fa fa-shopping-cart" aria-hidden="true"></i> CART
              <span class="cart-item-number badge">1</span>
            </a>
              
        </button>

        <div class="main-navbar-more-buttons">
          
          <button class="btn btn-default navbar-cart-btn">
            <a href={%url 'wishlist' %} class="header-wishlist-btn header-cart-btn">
              <i class="fa fa-shopping-wishlist" aria-hidden="true"></i> WISHLIST
              <span class="wishlist-item-number badge">0</span>
            </a>
          </button>
            <div class="dropdown">
              {% if siteuser %}
              <a href="" class="btn btn-default navbar-user-btn dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">
                <i class="fa fa-user" aria-hidden="true"></i>
                {{siteuser.customer.Customer_First_Name}}
                <i class="fa fa-caret-down" aria-hidden="true"></i>
              </a>
              <ul class="dropdown-menu user-action-list">
                <li><a href="{%url "user-dashboard"%}">Dashboard</a></li>
                <li><a href="{%url "user-orders" %}">Orders</a></li>
                <li><a href="{%url "coupons" %}">Your Coupons</a></li>
                <li><a href="{%url "credits" %}">Your Credits</a></li>
                <li><a href="{%url "signout" %}">Log Out</a></li>
              </ul>
                {% else %}
                <a href="" class="btn btn-default navbar-user-btn dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">
                <i class="fa fa-user" aria-hidden="true"></i>
                MY ACCOUNT
                <i class="fa fa-caret-down" aria-hidden="true"></i>

              </a>
              <ul class="dropdown-menu user-action-list">
                <li><a href="/signin/">Login</a></li>
                <li><a href="/register/">Sign Up</a></li>
              </ul>
              {%endif%}
        </div>

      </div>

      <div class="search-form">
        <form class="main-navbar-form">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search">
            <button type="button" name="button" class="btn btn-default search-btn">
              <i class="fa fa-search" aria-hidden="true"></i>
            </button>
          </div>
        </form>
      </div>

      <div class="navbar-mobile-list" id="full-list">
        <div class="mobile-list-header">
          <div class="main-toggle-button">
              <button id="navbar-toggle-button" class="main-navbar-button visible-xs-inline btn btn-default small-button">
                    <i class="fa fa-times" aria-hidden="true"></i>
              </button>
          </div>
          <div class="logo">
            <a href="/">
              <img class="logo" src="{% static 'main/images/logo.png' %}" />
            </a>
          </div>

        </div>
        <ul>
          {% for base in base_category_list%}
              <li class="mobile-list-link"><strong>{{ base.Base_Category }}</strong>
                <i class="fa fa-plus pull-right" aria-hidden="true"></i>
                <ul class="mobile-list-sub">
                    {% for  sub in base.subcategory_set.all %}

                        <li><a href="/product/{{base.Base_Category|lower}}/{{sub.Sub_Category|lower}}/">{{sub.Sub_Category_alias}}</a></li>

                    {% endfor %}
                </ul>
              </li>
          {% endfor %}
        </ul>
        <ul>
          <li><a href="{%url "user-orders"%}">My Orders</a></li>
          <li><a href="{%url "checkout"%}">My Cart</a></li>
          <li><a href="{%url "credits"%}">My FashVolts Credits</a></li>
          <li><a href="/signin/">My Account</a></li>
        </ul>
        <ul>
          <li><a href="#">About</a></li>
          <li><a href="#">Contact Us</a></li>
          <li><a href="#">Legal</a></li>
          <li><a href="#">Sell With Us</a></li>
          <li><a href="#">Offers and deals</a></li>
        </ul>
      </div>
    </div>
</nav>